In [ ]:
## make three dataframe in python and save them as three .csv files and  then saving the files in.csv files.

In [57]:
#import the pandas as a pd 
import pandas as pd

In [58]:
#create the project DataFrame
project = pd.DataFrame({
    #adding the cloumn name and row information
    "id" : ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003",
           "A001","A004","A004","A005"],
           
    "project":  ["project 1","project 2","project 3","project 4","project 5","project 6",
                  "project 7","project 8","project 9","project 10","project 11","project 12",
                  "project 13", "project 14"],
    
    "cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],

    "status": [ "Finished","Ongoing","Finished","Ongoing","Finished","Failed",
    "Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
                       })
#printing the output
project

      id     project       cost    status
0   A001   project 1  1002000.0  Finished
1   A002   project 2  2000000.0   Ongoing
2   A003   project 3  4500000.0  Finished
3   A004   project 4  5500000.0   Ongoing
4   A005   project 5        NaN  Finished
5   A002   project 6   680000.0    Failed
6   A005   project 7   400000.0  Finished
7   A003   project 8   350000.0    Failed
8   A001   project 9        NaN   Ongoing
9   A003  project 10   300000.0  Finished
10  A001  project 11  2000000.0    Failed
11  A004  project 12  1000000.0   Ongoing
12  A004  project 13  3000000.0  Finished
13  A005  project 14   200000.0  Finished

In [59]:
#create employee dataframe

employee = pd.DataFrame({

     #adding the cloumn name and row information
    "id":[ "A001","A002","A003","A004","A005"],

    "name":[ "John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],

    "gender": ["M","F","M","F","F"],

    "city" : [ "Paris","Londaon","Berlin","Newyork","Madrid"],
    "age":[25,27,29,31,30]
})
#printing the output
employee

     id             name gender     city  age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F  Londaon   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [60]:
#create a seniority DataFrame
seniority = pd.DataFrame ({
    # #adding the cloumn name and row information
    "id": ["A001","A002","A003","A004","A005"],
    "designation level":[2,2,3,2,3]
})
#printing the output
seniority

     id  designation level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [61]:
#saving the DataFrame of  project,employee and seniority as a csv files 

project .to_csv("project.csv",index= False)
employee.to_csv("employee.csv",index=False)
seniority.to_csv("seniority.csv",index=False)

In [62]:
#Afer saving the DataFrame reading the file saved in the csv files

project = pd.read_csv("project.csv")
employee = pd.read_csv("employee.csv")
seniority = pd.read_csv("seniority.csv")

In [63]:
## The cost column in the dataframe “Project” has some missing values. 
#These missing values replace the missing values by running average. Use the “For” loop for this task.

In [64]:
project = pd.read_csv("project.csv")

In [65]:
(project)

      id     project       cost    status
0   A001   project 1  1002000.0  Finished
1   A002   project 2  2000000.0   Ongoing
2   A003   project 3  4500000.0  Finished
3   A004   project 4  5500000.0   Ongoing
4   A005   project 5        NaN  Finished
5   A002   project 6   680000.0    Failed
6   A005   project 7   400000.0  Finished
7   A003   project 8   350000.0    Failed
8   A001   project 9        NaN   Ongoing
9   A003  project 10   300000.0  Finished
10  A001  project 11  2000000.0    Failed
11  A004  project 12  1000000.0   Ongoing
12  A004  project 13  3000000.0  Finished
13  A005  project 14   200000.0  Finished

In [66]:
running_sum = 0
count = 0

# calculate running average and replacing the missing values using the if statement
for i in range(len(project)):
    if pd.notna(project.loc[i, "cost"]):
        running_sum += project.loc[i, "cost"]
        count += 1
    else:
        avg = running_sum / count
        project.loc[i, "cost"] = avg
        running_sum += avg
        count += 1
#display the update of project 
(project)

      id     project       cost    status
0   A001   project 1  1002000.0  Finished
1   A002   project 2  2000000.0   Ongoing
2   A003   project 3  4500000.0  Finished
3   A004   project 4  5500000.0   Ongoing
4   A005   project 5  3250500.0  Finished
5   A002   project 6   680000.0    Failed
6   A005   project 7   400000.0  Finished
7   A003   project 8   350000.0    Failed
8   A001   project 9  2210312.5   Ongoing
9   A003  project 10   300000.0  Finished
10  A001  project 11  2000000.0    Failed
11  A004  project 12  1000000.0   Ongoing
12  A004  project 13  3000000.0  Finished
13  A005  project 14   200000.0  Finished

In [67]:
#Split the name column in the Employee dataframe into two new columns “First Name”, and “Last Name” and remove the older “name” column.

In [90]:
#reading the employee DataFrame 
employee = pd.read_csv("employee.csv")

# using the spliting the  name cloumn into first name and last name 
employee[['First Name', 'Last Name']] =employee ['name'].str.split(' ', expand=True)

#remove the original name cloumn 
employee.drop('name', axis=1, inplace=True)

##display the update of employee
(employee)

     id gender     city  age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F  Londaon   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [69]:
## Join all three dataframes in one single dataframe. Name it “Final”

In [70]:
#mereging the above result with project and employee 
result_1 = pd.merge(left = project,right = employee ,  on = "id")

#printing the output
result_1

,id,project,cost,status,gender,city,age,First Name,Last Name
0,A001,project 1,1002000.0,Finished,M,Paris,25,John,Alter
1,A002,project 2,2000000.0,Ongoing,F,Londaon,27,Alice,Luxumberg
2,A003,project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine
3,A004,project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra
4,A005,project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny
5,A002,project 6,680000.0,Failed,F,Londaon,27,Alice,Luxumberg
6,A005,project 7,400000.0,Finished,F,Madrid,30,Amy,Johny
7,A003,project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine
8,A001,project 9,2210312.5,Ongoing,M,Paris,25,John,Alter
9,A003,project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine
10,A001,project 11,2000000.0,Failed,M,Paris,25,John,Alter
11,A004,project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra
12,A004,project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra
13,A005,project 14,200000.0,Finished,F,Madrid,30,Amy,Johny

In [71]:
# reading the all csv files

project = pd.read_csv("project.csv")
employee = pd.read_csv("employee.csv")
seniority = pd.read_csv("seniority.csv")

#mereging the above result with project and employee 
result = pd.merge(left = project,right = employee ,  on = "id")

#printing the output
result

,id,project,cost,status,name,gender,city,age
0,A001,project 1,1002000.0,Finished,John Alter,M,Paris,25
1,A002,project 2,2000000.0,Ongoing,Alice Luxumberg,F,Londaon,27
2,A003,project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29
3,A004,project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31
4,A005,project 5,NaN,Finished,Amy Johny,F,Madrid,30
5,A002,project 6,680000.0,Failed,Alice Luxumberg,F,Londaon,27
6,A005,project 7,400000.0,Finished,Amy Johny,F,Madrid,30
7,A003,project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29
8,A001,project 9,NaN,Ongoing,John Alter,M,Paris,25
9,A003,project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29
10,A001,project 11,2000000.0,Failed,John Alter,M,Paris,25
11,A004,project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31
12,A004,project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31
13,A005,project 14,200000.0,Finished,Amy Johny,F,Madrid,30

In [72]:
#again merging the result and seniority for final 

import pandas as pd

#merge the above result with seniority DataFrame
final = pd.merge(left = result_1,right = seniority ,  on = "id")

#showing the final output merging all DataFrame
final

,id,project,cost,status,gender,city,age,First Name,Last Name,designation level
0,A001,project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,project 2,2000000.0,Ongoing,F,Londaon,27,Alice,Luxumberg,2
2,A003,project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,project 6,680000.0,Failed,F,Londaon,27,Alice,Luxumberg,2
6,A005,project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

In [73]:
#again merging the result and seniority for final 

import pandas as pd

#merge the above result with seniority DataFrame
final = pd.merge(left = result,right = seniority ,  on = "id")

#showing the final output merging all DataFrame
final

,id,project,cost,status,name,gender,city,age,designation level
0,A001,project 1,1002000.0,Finished,John Alter,M,Paris,25,2
1,A002,project 2,2000000.0,Ongoing,Alice Luxumberg,F,Londaon,27,2
2,A003,project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29,3
3,A004,project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31,2
4,A005,project 5,NaN,Finished,Amy Johny,F,Madrid,30,3
5,A002,project 6,680000.0,Failed,Alice Luxumberg,F,Londaon,27,2
6,A005,project 7,400000.0,Finished,Amy Johny,F,Madrid,30,3
7,A003,project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29,3
8,A001,project 9,NaN,Ongoing,John Alter,M,Paris,25,2
9,A003,project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29,3
10,A001,project 11,2000000.0,Failed,John Alter,M,Paris,25,2
11,A004,project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31,2
12,A004,project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31,2
13,A005,project 14,200000.0,Finished,Amy Johny,F,Madrid,30,3

In [74]:
## Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project cost only to employees who have finished the projects.

In [75]:
#improting the numpy library
import numpy as np

#create a bonus column based on final status
final["bonus"] = np.where(
        final["status"] == "Finished",
        final["cost"] * 0.05,
        0
    )

#display the final Data Frame
(final)

,id,project,cost,status,name,gender,city,age,designation level,bonus
0,A001,project 1,1002000.0,Finished,John Alter,M,Paris,25,2,50100.0
1,A002,project 2,2000000.0,Ongoing,Alice Luxumberg,F,Londaon,27,2,0.0
2,A003,project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29,3,225000.0
3,A004,project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31,2,0.0
4,A005,project 5,NaN,Finished,Amy Johny,F,Madrid,30,3,NaN
5,A002,project 6,680000.0,Failed,Alice Luxumberg,F,Londaon,27,2,0.0
6,A005,project 7,400000.0,Finished,Amy Johny,F,Madrid,30,3,20000.0
7,A003,project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29,3,0.0
8,A001,project 9,NaN,Ongoing,John Alter,M,Paris,25,2,0.0
9,A003,project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29,3,15000.0
10,A001,project 11,2000000.0,Failed,John Alter,M,Paris,25,2,0.0
11,A004,project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31,2,0.0
12,A004,project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31,2,150000.0
13,A005,project 14,200000.0,Finished,Amy Johny,F,Madrid,30,3,10000.0

In [76]:
#improting the numpy library

import numpy as np

##create a bonus column based on project status
project["bonus"] = np.where(
        project["status"] == "Finished",
        project["cost"] * 0.05,
        0
    )
# display the project Dataframe
(project)

      id     project       cost    status     bonus
0   A001   project 1  1002000.0  Finished   50100.0
1   A002   project 2  2000000.0   Ongoing       0.0
2   A003   project 3  4500000.0  Finished  225000.0
3   A004   project 4  5500000.0   Ongoing       0.0
4   A005   project 5        NaN  Finished       NaN
5   A002   project 6   680000.0    Failed       0.0
6   A005   project 7   400000.0  Finished   20000.0
7   A003   project 8   350000.0    Failed       0.0
8   A001   project 9        NaN   Ongoing       0.0
9   A003  project 10   300000.0  Finished   15000.0
10  A001  project 11  2000000.0    Failed       0.0
11  A004  project 12  1000000.0   Ongoing       0.0
12  A004  project 13  3000000.0  Finished  150000.0
13  A005  project 14   200000.0  Finished   10000.0

In [77]:
## Demote the designation level by 1, whose projects have status “fail”. Delete the employees record whose designation level is above 4.

In [78]:
#reduce the desiganation level by 1 for failed project

final.loc[final["status"] == "Failed", "designation level"] -= 1

#delet employee whose designation level is above 4 
fianl = final[final["designation level"] <= 4]

#display the update find DataFarme
final

,id,project,cost,status,name,gender,city,age,designation level,bonus
0,A001,project 1,1002000.0,Finished,John Alter,M,Paris,25,2,50100.0
1,A002,project 2,2000000.0,Ongoing,Alice Luxumberg,F,Londaon,27,2,0.0
2,A003,project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29,3,225000.0
3,A004,project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31,2,0.0
4,A005,project 5,NaN,Finished,Amy Johny,F,Madrid,30,3,NaN
5,A002,project 6,680000.0,Failed,Alice Luxumberg,F,Londaon,27,1,0.0
6,A005,project 7,400000.0,Finished,Amy Johny,F,Madrid,30,3,20000.0
7,A003,project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29,2,0.0
8,A001,project 9,NaN,Ongoing,John Alter,M,Paris,25,2,0.0
9,A003,project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29,3,15000.0
10,A001,project 11,2000000.0,Failed,John Alter,M,Paris,25,1,0.0
11,A004,project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31,2,0.0
12,A004,project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31,2,150000.0
13,A005,project 14,200000.0,Finished,Amy Johny,F,Madrid,30,3,10000.0

In [79]:
## Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [80]:
#import numpy library
import numpy as np

In [81]:
#add "Mr" for a male and "Mrs" for a female employees

final["name"] = np.where(
    final["gender"] == "M",
    "Mr. " + final["name"],
    "Mrs. " + final["name"]
)

#remove the gender column
final.drop("gender", axis = 1 ,inplace = True)

#display the update final DataFrame
(final)

,id,project,cost,status,name,city,age,designation level,bonus
0,A001,project 1,1002000.0,Finished,Mr. John Alter,Paris,25,2,50100.0
1,A002,project 2,2000000.0,Ongoing,Mrs. Alice Luxumberg,Londaon,27,2,0.0
2,A003,project 3,4500000.0,Finished,Mr. Tom Sabestine,Berlin,29,3,225000.0
3,A004,project 4,5500000.0,Ongoing,Mrs. Nina Adgra,Newyork,31,2,0.0
4,A005,project 5,NaN,Finished,Mrs. Amy Johny,Madrid,30,3,NaN
5,A002,project 6,680000.0,Failed,Mrs. Alice Luxumberg,Londaon,27,1,0.0
6,A005,project 7,400000.0,Finished,Mrs. Amy Johny,Madrid,30,3,20000.0
7,A003,project 8,350000.0,Failed,Mr. Tom Sabestine,Berlin,29,2,0.0
8,A001,project 9,NaN,Ongoing,Mr. John Alter,Paris,25,2,0.0
9,A003,project 10,300000.0,Finished,Mr. Tom Sabestine,Berlin,29,3,15000.0
10,A001,project 11,2000000.0,Failed,Mr. John Alter,Paris,25,1,0.0
11,A004,project 12,1000000.0,Ongoing,Mrs. Nina Adgra,Newyork,31,2,0.0
12,A004,project 13,3000000.0,Finished,Mrs. Nina Adgra,Newyork,31,2,150000.0
13,A005,project 14,200000.0,Finished,Mrs. Amy Johny,Madrid,30,3,10000.0

In [82]:
#add "Mr" for a male and "Mrs" for a female employees

employee["name"] = np.where(
    employee["gender"] == "M",
    "Mr. " + employee["name"],
    "Mrs. " + employee["name"]
)
#remove the gender column 
employee.drop("gender", axis = 1 ,inplace = True)

#display the update employee DataFrame
(employee)

     id                  name     city  age
0  A001        Mr. John Alter    Paris   25
1  A002  Mrs. Alice Luxumberg  Londaon   27
2  A003     Mr. Tom Sabestine   Berlin   29
3  A004       Mrs. Nina Adgra  Newyork   31
4  A005        Mrs. Amy Johny   Madrid   30

In [83]:
## Promote designation level by 1 for the employees whose age is more than 29 years using IF condition.

In [84]:
#loop through each employee record
for i in  final.index:

#check whether employee age is greater than 29 
    if final.loc[i, "age"] > 29:

# equal to the designation level by 1 
        final.loc[i, "designation level"] = 1

#display the update final DataFrame
final

,id,project,cost,status,name,city,age,designation level,bonus
0,A001,project 1,1002000.0,Finished,Mr. John Alter,Paris,25,2,50100.0
1,A002,project 2,2000000.0,Ongoing,Mrs. Alice Luxumberg,Londaon,27,2,0.0
2,A003,project 3,4500000.0,Finished,Mr. Tom Sabestine,Berlin,29,3,225000.0
3,A004,project 4,5500000.0,Ongoing,Mrs. Nina Adgra,Newyork,31,1,0.0
4,A005,project 5,NaN,Finished,Mrs. Amy Johny,Madrid,30,1,NaN
5,A002,project 6,680000.0,Failed,Mrs. Alice Luxumberg,Londaon,27,1,0.0
6,A005,project 7,400000.0,Finished,Mrs. Amy Johny,Madrid,30,1,20000.0
7,A003,project 8,350000.0,Failed,Mr. Tom Sabestine,Berlin,29,2,0.0
8,A001,project 9,NaN,Ongoing,Mr. John Alter,Paris,25,2,0.0
9,A003,project 10,300000.0,Finished,Mr. Tom Sabestine,Berlin,29,3,15000.0
10,A001,project 11,2000000.0,Failed,Mr. John Alter,Paris,25,1,0.0
11,A004,project 12,1000000.0,Ongoing,Mrs. Nina Adgra,Newyork,31,1,0.0
12,A004,project 13,3000000.0,Finished,Mrs. Nina Adgra,Newyork,31,1,150000.0
13,A005,project 14,200000.0,Finished,Mrs. Amy Johny,Madrid,30,1,10000.0

In [85]:

#check whether employee age is greater than 29 
for i in  final.index:
    
#check whether employee age is greater than 29
    if final.loc[i, "age"] > 29:

#increase designation level by 1 
        final.loc[i, "designation level"] += 1

#display the update final DataFrame
final

,id,project,cost,status,name,city,age,designation level,bonus
0,A001,project 1,1002000.0,Finished,Mr. John Alter,Paris,25,2,50100.0
1,A002,project 2,2000000.0,Ongoing,Mrs. Alice Luxumberg,Londaon,27,2,0.0
2,A003,project 3,4500000.0,Finished,Mr. Tom Sabestine,Berlin,29,3,225000.0
3,A004,project 4,5500000.0,Ongoing,Mrs. Nina Adgra,Newyork,31,2,0.0
4,A005,project 5,NaN,Finished,Mrs. Amy Johny,Madrid,30,2,NaN
5,A002,project 6,680000.0,Failed,Mrs. Alice Luxumberg,Londaon,27,1,0.0
6,A005,project 7,400000.0,Finished,Mrs. Amy Johny,Madrid,30,2,20000.0
7,A003,project 8,350000.0,Failed,Mr. Tom Sabestine,Berlin,29,2,0.0
8,A001,project 9,NaN,Ongoing,Mr. John Alter,Paris,25,2,0.0
9,A003,project 10,300000.0,Finished,Mr. Tom Sabestine,Berlin,29,3,15000.0
10,A001,project 11,2000000.0,Failed,Mr. John Alter,Paris,25,1,0.0
11,A004,project 12,1000000.0,Ongoing,Mrs. Nina Adgra,Newyork,31,2,0.0
12,A004,project 13,3000000.0,Finished,Mrs. Nina Adgra,Newyork,31,2,150000.0
13,A005,project 14,200000.0,Finished,Mrs. Amy Johny,Madrid,30,2,10000.0

In [86]:
## Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost

In [91]:
#calculate total project cost for each employee
total_cost = project.groupby("id")[["cost"]].sum().reset_index()

#merge with employee DataFrame
total_project_cost = pd.merge(
    employee[["id","First Name"]],
    total_cost,
    on ="id",
    how = "inner"
)

#rename the cost column 
total_project_cost.rename(columns={"cost": "total_cost"}, inplace = True )

#save as csv files
total_project_cost.to_csv("total_project_cost.csv", index = False )

#display the DataFrame
(total_project_cost)

     id First Name  total_cost
0  A001       John   3002000.0
1  A002      Alice   2680000.0
2  A003        Tom   5150000.0
3  A004       Nina   9500000.0
4  A005        Amy    600000.0

In [88]:
# Print all the employee details whose city name contains the letter “o” in it.

In [89]:

# selecting the employee whose city name contains the letter "o" 
employee_o = employee[employee["city"].str.contains("o",case= False , na = False)]

# display the result filtered employee details
employee_o

     id                  name     city  age
1  A002  Mrs. Alice Luxumberg  Londaon   27
3  A004       Mrs. Nina Adgra  Newyork   31